baseURL = "https://ajchatham.com/"
languageCode = "en-us"
canonifyurls = true
relativeURLs = true
googleAnalytics = "G-KJ9VP98G92"

pygmentsCodeFences = true
pygmentsUseClasses = true

title = "Andy Chatham's blog"
name = "Andy Chatham's blog"
description = "a blog"

[markup.goldmark.renderer]
unsafe = true
